services:
  php:
    build:
      context: .docker/php
    networks:
      - backend
    volumes:
      - ./backend/:/var/www/html/

  nginx:
    build:
      context: .docker/nginx
    ports:
      - "8080:80"
    networks:
      - backend
    volumes:
      - ./backend/:/var/www/html/

networks:
  backend:
    driver: bridge
